apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: roboshop-admin
  namespace: roboshop
subjects:
- kind: User
  name: sai 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: roboshop-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: roboshop-admin
subjects:
- kind: User
  name: sai
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: roboshop-admin
  apiGroup: rbac.authorization.k8s.io